### ISSUE TITLE
Extension Support Tracker for 2.0.0 Release

### ISSUE THREAD

**Issue by PiyushRaj927** [Samagra-Development/WarpSQL#123]
The following extensions need implementation for the upcoming 2.0.0 release.
#### Extensions to transfer from `main` branch
- [ ] Citus 
- [ ] PostGIS 
- [ ] ZomboDB 
- [ ] Pg Repack
- [ ] PG Auto Failover
- [ ] HyperLogLog

#### Extensions to implement 
- [ ] https://github.com/Samagra-Development/WarpSQL/issues/6
- [ ] https://github.com/Samagra-Development/WarpSQL/issues/10
- [ ] https://github.com/Samagra-Development/WarpSQL/issues/34
- [ ] https://github.com/Samagra-Development/WarpSQL/issues/61
- [ ] https://github.com/Samagra-Development/WarpSQL/issues/107

**Each implementation should be accompanied by updated smoke tests**

**Comment by singhalkarun** [comment]
- [ ] @PiyushRaj927 to create a draft release with changelog with tag 2.0.0
- [ ] Release docker image to github with tag 2.0.0 and latest

**Comment by sooraj1002** [comment]
@PiyushRaj927 could you please pick up zomboDB and BM25 integration?
